services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: runner
    environment:
      CONFIG_FILE: "/app/config.toml"
    volumes:
      - ../src:/app/src
      - ./config.toml:/app/config.toml
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
